### ISSUE TITLE
GeoServer container writes

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/geonode#75]
root@e70d55112a52:/usr/local/tomcat/webapps/geoserver/WEB-INF# cat web.xml
```xml       
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-app PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN" "http://java.sun.com/dtd/web-app_2_3.dtd">
<web-app>
    <display-name>GeoServer</display-name>
  
      <context-param>
    <param-name>serviceStrategy</param-name>
    <!-- Meaning of the different values :
         
         PARTIAL-BUFFER2
         - Partially buffers the first xKb to disk. Once that has buffered, the the 
           result is streamed to the user. This will allow for most errors to be caught
           early. 
           
         BUFFER
         - stores the entire response in memory first, before sending it off to
           the user (may run out of memory)

         SPEED
         - outputs directly to the response (and cannot recover in the case of an
           error)

         FILE
         - outputs to the local filesystem first, before sending it off to the user
      -->
    <param-value>FILE</param-value>
  </context-param>
   ...
```

Should probably be `PARTIAL-BUFFER2` instead.

**Comment by fvanderbiest** [comment]
See http://docs.geoserver.org/stable/en/user/production/config.html#set-a-service-strategy

**Comment by Vampouille** [comment]
Fixed with https://github.com/camptocamp/geonode-geoserver-docker/commit/4a21fd55d14c3f600f643459e84846f69c0e4515 and apply with https://github.com/camptocamp/terraform-geonode/pull/18

**Comment by Vampouille** [comment]
Let's wait some days to see if this fix this issue

**Comment by Vampouille** [comment]
> Let's wait some days to see if this fix this issue

It seems that this fix don't have any effect on geoserver. We need to find another way to avoid writes in container.

**Comment by Vampouille** [comment]
The temp file looks like a raw raster, see metadata in headers
```
# head -6 imageio4029523879742583128.tmp 
NCOLS 43200
NROWS 16744
XLLCORNER -180.0
YLLCORNER -55.90833333341696
CELLSIZE 0.00833333376795053
NODATA_VALUE -3.402823E38
```

**Comment by fvanderbiest** [comment]
The service is currently DOWN, due to disk being filled with those temp files. We're currently working on it.

**Comment by fvanderbiest** [comment]
On https://www.geonode-gfdrrlab.org/geoserver/web/wicket/bookmarkable/org.geoserver.wcs.web.WCSAdminPage?4 the read/generation limits for WCS are not set. What would be a reasonable setting here ? 1Gb or less ?

**Comment by fvanderbiest** [comment]
Since I changed the value to 1Gb, there are errors in the logs, which confirm that too much data is being pulled out of GeoServer WCS service.
```
2018-02-26 20:33:51,428 ERROR [geoserver.ows] - 
org.vfny.geoserver.wcs.WcsException: This request is trying to read too much data, the limit is 1024MB but the actual amount of bytes to be read is 2759.33MB
	at org.vfny.geoserver.util.WCSUtils.checkInputLimits(WCSUtils.java:326)
	at org.geoserver.wcs.DefaultWebCoverageService100.getCoverage(DefaultWebCoverageService100.java:492)
```
Wondering if that's not due to thinkhazard

**Comment by fvanderbiest** [comment]
The log message says `the actual amount of bytes to be read is 2759.33MB` but there are no files beyond 656M on the server:
```
sftp@ADMIN-gfdrr-prod-app:/mnt/geoserver_geodata$ sudo find . -size +200M -exec ls -alh {} \;
-rw-r--r-- 1 sftp sftp 563M May 14  2015 ./hazard/mrcofld_rp100_100m/mrcofld_rp100_100m.geotiff
-rw-r--r-- 1 sftp sftp 563M May 14  2015 ./hazard/mrcofld_rp25_100m/mrcofld_rp25_100m.geotiff
-rw-r--r-- 1 sftp sftp 563M May 14  2015 ./hazard/mrcofld_rp2_100m/mrcofld_rp2_100m.geotiff
-rw-r--r-- 1 sftp sftp 563M May 14  2015 ./hazard/mrcofld_rp10_100m/mrcofld_rp10_100m.geotiff
-rw-r----- 1 sftp sftp 656M Jun 23  2017 ./hazard/global_reclassify/global_reclassify.geotiff
```

**Comment by fvanderbiest** [comment]
> Wondering if that's not due to thinkhazard

Nope, since https://www.geonode-gfdrrlab.org/api/layers/ does not mention any `download_url` using WCS

**Comment by fvanderbiest** [comment]
@afabiani do you guys at GeoSolutions know how to prevent GeoServer from writing those imageio4029523879742583128.tmp files in tomcat's temp folder ?

**Comment by afabiani** [comment]
@fvanderbiest hello, currently I don't think this is possible since those files are created by the ImageIO streaming.

Maybe it could be possible to write them on a custom temporary folder and delete them with a cron job or something.
In order to do that you should be able to set the "java.io.tmpdir" property on JAVA_OPTS 

Something like -Djava.io.tmpdir=<full_temp_dir_path>

**Comment by fvanderbiest** [comment]
Hi Alessio,
Thanks for your answer, we'll try this ASAP !

https://github.com/camptocamp/geonode-geoserver-docker/pull/1 to be reviewed

**Comment by fvanderbiest** [comment]
Here's a request generating too much data (makes the geoserver fail - don't click the link): https://www.geonode-gfdrrlab.org/geoserver/wcs?crs=EPSG%3A4326&service=WCS&format=GeoTIFF&request=GetCoverage&height=16744&width=43200&version=1.0.0&BBox=-187.27200037926434%2C-126.59567035338198%2C187.27201915472722%2C154.3123442971117&Coverage=hazard%3Ass_muis_rp0100m&access_token=a6e3c7b88c8911e7950f02a6770a206b from https://www.geonode-gfdrrlab.org/layers/hazard%3Ass_muis_rp0100m

The original file is https://www.geonode-gfdrrlab.org/uploaded/layers/ss_muis_rp0100m.tif (40 Mb with an LZW compression)

**Comment by fvanderbiest** [comment]
From http://docs.geoserver.org/stable/en/user/services/wcs/configuration.html: "Finally the resulting raster will be encoded in the output format. Depending on the output format structure the size of the result might be higher than the in memory size (ArcGrid case) or smaller (for example in the case of GeoTIFF output, which is normally LZW compressed)"
Strangely this does seem to apply here (the WCS-downloaded file is uncompressed)

**Comment by afabiani** [comment]
@fvanderbiest it is not that easy. WCS protocol is not aware, and does not preserve the original raster structure. For WCS 2.0.1 there are some extensions for GeoTiffs that should allow you to select the best "overview" and "interpolation" accordingly to the requested area.

Adding this parameter to the request

overviewpolicy=[NEAREST | QUALITY | SPEED]

should allow you to get a smaller size GeoTiff, but, I'm afraid, this really depends on it's internal structure. If it does not contain internal overviews, I guess the WCS will always give you back the full size, uncompressed raster.

Most probably the best way would be to be to add another download link on the GUI allowing the user to get the original file directly instead of passing through the WCS.

WCS is useful only to subset/filter/re-project/convert to another format. Not much useful to get the original data.

**Comment by stufraser1** [comment]
GeoSolutions have submitted a PR containing new code to perform direct download of rasters in GeoNode rather than WCS - https://github.com/GeoNode/geonode/pull/3674
Is it possible to implement this in Labs Geonode?
